spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/im-wx?useUnicode=true&characterEncoding=utf8
     username: root
     password: yanghua883721
     driver-class-name: com.mysql.jdbc.Driver

